PROYECTO/cliente/urls.py
from django.urls import path
from cliente import views
app_name = "cliente"

urlpatterns = [
    path("",views.home,name="Home"),
    path("cliente_create.html",views.cliente_create,name="cliente_create"),
    
]

PROYECTO/config/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

PROYECTO/core/urls.py
from django.urls import path
app_name = "core"
from . import views

urlpatterns = [
    path("",views.home,name="Home"),
]

PROYECTO/producto/urls.py
from django.urls import path
from . import views
app_name = "producto"

urlpatterns = [
    path("",views.home,name="Home"),
    path("productocategoria/create/",views.productocategoria_create,name="productocategoria_create"),
    path("productos_buscador_categoria/",views.home_1,name="buscador_productos"),
    path("productos_caracteristicas/<int:pk>",views.productos_caracteristicas,name="productos_caracteristicas")

]

PROYECTO/cliente/models.py
from django.db import models

class suscripcion(models.Model):
    nivel = models.CharField(max_length=50)
    def __str__(self):

        return self.nivel

class Pais(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):

        return self.nombre
    
    class Meta:
        verbose_name_plural = 'Países'

class cliente(models.Model):
        nombre = models.CharField(max_length=200)

        apellido = models.CharField(max_length=50)

        nacimiento = models.DateField(null=True)

        pais_origen_id = models.ForeignKey(Pais, on_delete=models.SET_NULL, null=True, verbose_name="País de origen")

        nivel_sus = models.ForeignKey(suscripcion, on_delete=models.SET_NULL, null=True, verbose_name="Nivel")

        def __str__(self):
             return self.nombre

            

PROYECTO/core/models.py
from django.db import models

# Create your models here.

PROYECTO/producto/models.py
from django.db import models

class ProductoCategoria(models.Model):
    nombre = models.CharField(max_length=200,unique=True)
    descripcion = models.CharField(max_length=250,null=True, blank=True,verbose_name='descripción')

    def __str__(self):
        return self.nombre
    
    class Meta:
        verbose_name = "categoría de productos"

class Origen(models.Model):
    Origen_producto= models.CharField(max_length=200,unique=True)
    def __str__(self):

     return self.Origen_producto

class Producto(models.Model):
    nombre = models.CharField(max_length=200)
    modelo_categoria = models.ForeignKey(ProductoCategoria, on_delete=models.SET_NULL, null=True, verbose_name="categoría de productos")
    precio_producto = models.PositiveBigIntegerField(verbose_name="Precio")
    Origen_producto = models.ForeignKey(Origen, on_delete=models.SET_NULL, null=True, verbose_name="Origen del producto")
    
    def __str__(self):

     return self.nombre
     

PROYECTO/cliente/forms.py
from django import forms
from . import models

class Clientes_form(forms.ModelForm):
    class Meta:
        model = models.cliente
        fields ="__all__"

PROYECTO/producto/forms.py
from django import forms
from . import models

class ProductoCategoriaForm(forms.ModelForm):
    class Meta:
        model = models.ProductoCategoria
        fields = "__all__"

class Producto_CreateForm(forms.ModelForm):
    class Meta:
        model = models.Producto
        fields = "__all__"

PROYECTO/cliente/views.py
from django.shortcuts import render, redirect
from django import forms
from . import models, forms

def home(request):
    consulta = request.GET.get("consulta", None)

    if consulta:
        query = models.cliente.objects.filter(nombre__icontains=consulta) 
    
    else:
        query = models.cliente.objects.all()

    context = {"clientes":query}
    
    return render(request,"cliente/index.html",context)

def cliente_create(request):
    if request.method == "POST":
        form = forms.Clientes_form(request.POST)
        if form. is_valid():
            form.save() 
            return redirect("cliente:Home")
    else:
        form = forms.Clientes_form()
    return render(request, "cliente/cliente_create.html",context={"form":form})
 

PROYECTO/core/views.py
from django.shortcuts import render

from django.shortcuts import render
from . import models

def home(request):
    return render(request,"core/index.html")

PROYECTO/producto/views.py
from django.shortcuts import render, redirect
from django import forms
from . import forms, models 

def home(request):
    consulta_productos = models.ProductoCategoria.objects.all()
    context = {"productos":consulta_productos}
    return render(request,"producto/index.html",context)

def home_1(request):
    consulta = request.GET.get("consulta", None)
    
    if consulta:
        query = models.ProductoCategoria.objects.filter(nombre__icontains=consulta)
    else:
        query = models.ProductoCategoria.objects.all()

    context = {"productos":query}
    return render(request,"producto/buscador_productos.html",context)

def productocategoria_create(request):
    if request.method == "POST":
        form = forms.ProductoCategoriaForm(request.POST)
        if form. is_valid():
            form.save()
            return redirect("producto:Home")
    else:
        form = forms.ProductoCategoriaForm()      
    return render(request, "Producto/productocategoria_create.html",context={"form":form})

def Producto_create(request):
    if request.method == "POST":
        form = forms.Producto_CreateForm(request.POST)
        if form. is_valid():
            form.save()
            return redirect("producto:Home")
        else:
            form = forms.Producto_CreateForm()
        return render(request,"Producto/producto_create.html",context = {"form":form})
    

def productos_caracteristicas(request,pk):
    query = models.Producto.objects.get(id=pk)
    return render(request,"productos_caracteristicas.html",context={"producto":query})

PROYECTO/cliente/templates/cliente/cliente_create.html
{% extends 'core/base.html' %}
{% load static %}

{% block contenido %}


<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" href="{% static 'core/css/estilos.css' %}">
        <title>Formulario de creación de clientes</title>
        <link rel="icon" type="image/x-icon" href="{% static 'core/assets/favicon.ico"' %}" />
    </head>

    <body>
      <section class="form-register">
        <h4>FORMULARIO DE REGISTRO DE CLIENTES</h4>
        <form action="" method="post">
          {% csrf_token %}
      
          <table>
            {{form.as_table}}
          </table>

          <input class="botons" type="submit" value="REGISTRAR">
        </form>
      </section>
        
      <a href="{% url 'core:Home' %}">
     
        <section class="page-section bg-primary" id="about">
          <div class="container px-4 px-lg-5">
              <div class="row gx-4 gx-lg-5 justify-content-center">
                  <div class="col-lg-8 text-center">
                      <h2 class="text-white mt-0">VOLVER AL INCIO</h2>
                  </div>
              </div>
          </div>
      </section>

        <footer class="footer text-faded text-center py-5">
            <div class="container"><p class="m-0 small">La Esquina del Sabor &copy; 2024</p></div>
        </footer>
        
    
{% endblock contenido %}

PROYECTO/cliente/templates/cliente/index.html
{% extends 'core/base.html' %}
{% load static %}
    {% block  titulo%}

    <section class="page-section">
      <div class="container">
          <div class="product-item">
              <div class="product-item-title d-flex">
                  <div class="bg-faded p-5 d-flex me-auto rounded">
                      <h2 class="section-heading mb-0">
                          
                          <span class="section-heading-lower">CLIENTES</span>
                          
                      </h2>
                    </div>
              </div>
          </div>
        </div>
    </section> 
    {% endblock titulo %}

    {% block contenido %}

    <div class="col-md-3 pb-4">
        <div class="card-body align-self-md-center my-1">
          <form action="{% url 'cliente:Home' %}" method="get">
            <input type="text" name="consulta" placeholder="Buscar..." style="background-color: rgb(221, 155, 68); color: rgb(255, 254, 253);
              width: 100%; /* Full width */
              padding: 10px; /* Padding */
              border: 10px solid burlywood; /* Border */
              border-radius: 50px; /* Rounded corners */
              font-size: 20px; /* Font size */
            ">
          </form>
        </div>
      </div>
    </div>

        
    <div class="row">
        {% for x in clientes %}
        <div class="col-md-3 pb-4">
          <div class="card mb-3" style="background-color: burlywood; color: black;">  <div class="card-body align-self-md-center my-1 ">
              <h5 class="card-title text-nowrap">{{ x.nombre }} {{x.apellido}}</h5>
              <p class="card-text">
                <span class="fw-bold">Nacionalidad:</span> {{ x.pais_origen_id }}<br>
                <span class="fw-bold">Nacimiento:</span> {{ x.nacimiento|date:"d/m/Y" }} <br>
                <span class="fw-bold">País de origen:</span> {{ x.pais_origen_id }}<br>
                <span class="fw-bold">Nivel:</span> {{ x.nivel_sus }}
                
              </p>
            </div>
          </div>
        </div>
        {% endfor %}
    </div>
      
    <div class="fs-3 pb-4 ">
      <a href="{% url 'cliente:cliente_create' %}">
        <h1 class="site-heading text-center text-faded d-none d-lg-block">
        <span class="site-heading-upper text-primary mb-3">CREAR CLIENTES</span></a>
    </div> 

    <a href="{% url 'core:Home' %}">
     
      <section class="page-section bg-primary" id="about">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-lg-8 text-center">
                    <h2 class="text-white mt-0">VOLVER AL INCIO</h2>
                </div>
            </div>
        </div>
    </section>


    </a>
        
      <footer class="footer text-faded text-center py-5">
        <div class="container"><p class="m-0 small">La Esquina del Sabor &copy; 2024</p></div>
    </footer>
    {% endblock contenido%}

PROYECTO/core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="keywords" content="Café"/>
        <meta name="description" content="" />
        <meta name="author" content="Matías Vargas" />
        <title>La Esquina del Sabor</title>
        <link rel="icon" type="image/x-icon" href="{% static 'core/assets/favicon.ico"' %}" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'core/css/styles.css' %}" rel="stylesheet" />
    </head>

    <body>
        <header>
            <h1 class="site-heading text-center text-faded d-none d-lg-block">
                <span class="site-heading-upper text-primary mb-3">La Esquina del Sabor</span>
                <span class="site-heading-lower">Tu Dosis de Felicidad en Taza</span>
            </h1>
        </header>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
            <div class="container px-4 px-lg-5">
                <div class="container">
                <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav" style="justify-content: flex-start;  my-2 my-lg-0">
                        <li class="nav-item"><a class="nav-link" href="{% url 'producto:Home' %}">PRODUCTOS</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'cliente:Home' %}">CLIENTES</a></li>
                      </ul>
                </div>
            </div>
        </nav>

        {% block titulo %}
        {% endblock titulo%}
        {% block contenido %}
        {% endblock contenido %}

        
</html>

PROYECTO/core/templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}
{% block titulo %}
{% endblock titulo %}
{% block contenido %}



<nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
    <div class="container px-4 px-lg-5">
        <div class="container">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ms-auto my-2 my-lg-0">
                <li class="nav-item"><a class="nav-link" href="{% url 'producto:Home' %}">PRODUCTOS</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'cliente:Home' %}">CLIENTES</a></li>
                <li class="nav-item"><a class="nav-link" href="#contact">CONTACTOS</a></li>
                <li class="nav-item"><a class="nav-link" href="#ABOUT">ABOUT</a></li>
            </ul>
        </div>
    </div>
</nav>
    
<section class="page-section clearfix">
    <div class="container">
        <div class="intro">
            <img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="{% static 'core/imagenes/intro.webp' %}" alt="..." />
            <div class="intro-text left-0 text-center bg-faded p-5 rounded">
                <h2 class="section-heading mb-4">
                    <span class="section-heading-upper">Café que enamora</span>
                    <P></P>
                    <span class="section-heading-lower">Un momento para disfrutar</span>
                </h2>
                <p class="mb-3">Cada taza de nuestro café artesanal de calidad comienza con ingredientes finamente seleccionados. Una vez que lo pruebes, nuestro café será una maravillosa adición a tu rutina diaria. ¡Te lo garantizamos!

                </p>
                <div class="intro-button mx-auto"><a class="btn btn-primary btn-xl" href="#!">Visit Us Today!</a></div>
            </div>
        </div>
    </div>
</section>

<section class="page-section cta">
    <div class="container">
        <div class="row">
            <div class="col-xl-9 mx-auto">
                <div class="cta-inner bg-faded text-center rounded">
                    <h2 class="section-heading mb-4">
                        <span class="section-heading-upper">Nuestra Promesa</span>
                        <P></P>
                        <span class="section-heading-lower">para vos</span>
                    </h2>
                    <p class="mb-0">Cuando ingresas a nuestro establecimiento para comenzar el día, estamos dedicados a brindarte un servicio amable, un ambiente cálido y, sobre todo, excelentes productos elaborados con ingredientes de la más alta calidad. Si no está satisfecho, háganoslo saber y haremos todo lo posible para arreglar las cosas.</p>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="page-section bg-primary" id="ABOUT">
    <img class="img-fluid rounded about-heading-img mb-3 mb-lg-0" src="{% static 'core/imagenes/about.webp'%}" alt="..." />
    <div class="container">
        <div class="about-heading-content">
            <div class="row">
                <div class="col-xl-9 col-lg-10 mx-auto">
                    <div class="bg-faded rounded p-5">
                        <h2 class="section-heading mb-4">
                            <span class="section-heading-upper">Café fuerte, mente fuerte</span>
                            <P></P>
                            <span class="section-heading-lower">ACERCA DE NUESTRO  CAFÉ</span>
                        </h2>
                        <p>Fundado en 1987, nuestro establecimiento ha estado sirviendo un esquisito café procedente de agricultores artesanales provenientes de varias regiones de América del Sur y Central. Nos dedicamos a viajar por el mundo, encontrar el mejor café y traerlo aquí en nuestra cafetería.</p>
                        <p class="mb-0">
                            Te garantizamos que caeras 
                            <em>encantado</em>
                            con nuestras deliciosas mezclas desde el momento en que entras hasta que terminas tu último sorbo.
                            Nos encantará formar parte de rutina, cuando sales con amigos o simplemente para disfrutar de un tiempo a solas.

                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


<section class="page-section cta">
    <div class="container">
        <div class="row">
            <div class="col-xl-9 mx-auto">
                <div class="cta-inner bg-faded text-center rounded">
                    <h2 class="section-heading mb-5">
                        <span class="section-heading-upper">VEN A VISITARNOS</span>
                        <span class="section-heading-lower">ESTAMOS ABIERTOS TODOS LOS DÍAS</span>
                    </h2>
                    <ul class="list-unstyled list-hours mb-5 text-left mx-auto">
                        <li class="list-unstyled-item list-hours-item d-flex">
                            Domingo
                            <span class="ms-auto">9:00 to 23:00 </span>
                        </li>
                        <li class="list-unstyled-item list-hours-item d-flex">
                            Lunes
                            <span class="ms-auto">7:00 to 22:00 </span>
                        </li>
                        <li class="list-unstyled-item list-hours-item d-flex">
                            Martes
                            <span class="ms-auto">7:00 to 22:00 </span>
                        </li>
                        <li class="list-unstyled-item list-hours-item d-flex">
                            Miércoles
                            <span class="ms-auto">7:00 to 22:00 </span>
                        </li>
                        <li class="list-unstyled-item list-hours-item d-flex">
                            Jueves
                            <span class="ms-auto">7:00 to 22:00 </span>
                        </li>
                        <li class="list-unstyled-item list-hours-item d-flex">
                            Viernes
                            <span class="ms-auto">7:00 to 22:00 </span>
                        </li>
                        <li class="list-unstyled-item list-hours-item d-flex">
                            Sábado
                            <span class="ms-auto">9:00 AM to 23:00 </span>
                        </li>
                    </ul>
                    <p class="address mb-5" style="font-size: 2em;">
                        <em>
                            <strong>Avenida Las Heras 2450</strong>
                            <br />
                            Recoleta, CABA
                        </em>
                    </p>
                    <p class="mb-0" style="font-size: 2em;">
                        <em>Te esperamos!</em>
                   </p>
                </div>
            </div>
        </div>
    </div>
</section>



<footer class="footer text-faded text-center py-5">
    <div class="container"><p class="m-0 small">La Esquina del Sabor &copy; 2024</p></div>
</footer>
<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
<!-- Core theme JS-->
<script src="{% static 'core/js/scripts.js' %}></script>



{% endblock contenido %}

PROYECTO/producto/templates/producto/buscador_productos.html
{% extends 'core/base.html' %}
{% load static %}

{% block contenido %}

<head>
    <link rel="stylesheet" href="{% static 'core/css/estilos.css' %}">
    <link rel="stylesheet" href="{% static 'core/css/estilos.css' %}">
</head>

<section class="page-section">
    <div class="container">
        <div class="product-item">
            <div class="product-item-title d-flex">
                <div class="bg-faded p-5 d-flex me-auto rounded">
                    <h2 class="section-heading mb-0">
                        
                        <span class="section-heading-lower">PRODUCTOS</span>
                        
                    </h2>
                  </div>
            </div>
        </div>
      </div>
  </section>  

  <div class="col-md-3 pb-4">
    <div class="card-body align-self-md-center my-1">
      <form action="{% url 'producto:buscador_productos' %}" method="get">
        <input type="text" name="consulta" placeholder="Buscar..." style="background-color: rgb(221, 155, 68); color: rgb(255, 254, 253);
          width: 100%; /* Full width */
          padding: 10px; /* Padding */
          border: 10px solid burlywood; /* Border */
          border-radius: 50px; /* Rounded corners */
          font-size: 20px; /* Font size */
        ">
      </form>
    </div>
  </div>
</div>

    <div class="row">
        {% for x in productos %}
        <div class="col-md-3 pb-4">
          <div class="card mb-3" style="background-color: burlywood; color: black;">  <div class="card-body align-self-md-center my-1 ">
              <h5 class="card-title text-nowrap">{{ x.nombre }} <a href="{% url 'producto:productos_caracteristicas' producto.id %}"> PRODUCTOS</a></h5>
              <p class="card-text">
                <span class="fw-bold">Descripción: </span> {{ x.descripcion }} <br>
            </div>
          </div>
        </div>
        {% endfor %}
    </div>

{% endblock contenido %}
<section class="page-section">
    <div class="container">
        <div class="product-item">
            <div class="product-item-title d-flex">
                <div class="bg-faded p-5 d-flex me-auto rounded">
                    <h2 class="section-heading mb-0">
                        <p></p>
                        <span class="section-heading-lower">CATEGORÍAS DE PRODUCTOS</span>
                    </h2>
                  </div>
            </div>
        </div>
      </div>
  </section>  

  <div class="col-md-3 pb-4">
    <div class="card mb-4" style="background-color: burlywood; color: black;">  
        <div class="card-body align-self-md-center my-1 ">
                <form action="{% url 'producto:Home' %}" method="get">
                <input type="text" name="consulta" placeholder="Buscar...">
                </form>
           
        </div>
    </div>
  </div>

    <div class="row">
        {% for x in productos %}
        <div class="col-md-3 pb-4">
          <div class="card mb-3" style="background-color: burlywood; color: black;">  <div class="card-body align-self-md-center my-1 ">
              <h5 class="card-title text-nowrap">{{ x.nombre }}</h5>
              <p class="card-text">
                <span class="fw-bold">Descripción: </span> {{ x.descripcion }} <br>
            </div>
          </div>
        </div>
        {% endfor %}
    </div>

    <a href="{% url 'core:Home' %}">

      <section class="page-section bg-primary" id="about">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-lg-8 text-center">
                    <h2 class="text-white mt-0">VOLVER AL INCIO</h2>
                </div>
            </div>
        </div>
      </section>

    <footer class="footer text-faded text-center py-5">
      <div class="container"><p class="m-0 small">La Esquina del Sabor &copy; 2024</p></div>
  </footer>

PROYECTO/producto/templates/producto/index.html
    {% extends 'core/base.html' %}
    {% load static %}
    {% block  titulo%}
    <section class="page-section">
      <div class="container">
          <div class="product-item">
              <div class="product-item-title d-flex">
                  <div class="bg-faded p-5 d-flex me-auto rounded">
                      <h2 class="section-heading mb-0"> 
                          <span class="section-heading-lower">PRODUCTOS HECHOS CON AMOR</span>
                      </h2>
                    </div>
              </div>
          </div>
        </div>
    </section>    
    {% endblock titulo %}

    {% block contenido %}

    <section class="page-section">
      <div class="container">
          <div class="product-item">
              <div class="product-item-title d-flex">
                  <div class="bg-faded p-5 d-flex ms-auto rounded">
                      <h2 class="section-heading mb-0">
                          <span class="section-heading-upper">Mezclado a la perfección</span>
                          <p></p>
                          <span class="section-heading-lower">Café & Té</span>
                      </h2>
                  </div>
              </div>
              <img class="product-item-img mx-auto d-flex rounded img-fluid mb-3 mb-lg-0" src="{% static 'core/imagenes/products-01_2.webp' %}" alt="..." />
              <div class="product-item-description d-flex me-auto">
                  <div class="bg-faded p-5 rounded"><p class="mb-0">
                    Cada vez que nos pida una bebida, le garantizamos que será una experiencia que valdrá la pena vivir. 
                    Ya sea nuestro mundialmente famoso capuchino venezolano, un refrescante té de hierbas helado o algo tan simple como una taza de café negro especial,
                    le aseguramos que volverá por más.          </p>
                  </div>
              </div>
      </div>
  </section>
  <section class="page-section">
      <div class="container">
          <div class="product-item">
              <div class="product-item-title d-flex">
                  <div class="bg-faded p-5 d-flex me-auto rounded">
                      <h2 class="section-heading mb-0">
                          <span class="section-heading-upper">LA MEJOR COMIDA</span>
                          <p></p>
                          <span class="section-heading-lower">DESAYUNO, ALMUERZO, MERIENDA Y CENA</span>
                      </h2>
                  </div>
              </div>
              <img class="product-item-img mx-auto d-flex rounded img-fluid mb-3 mb-lg-0" src="{% static 'core/imagenes/products-02.webp' %}" alt="..." />
              <div class="product-item-description d-flex ms-auto">
                  <div class="bg-faded p-5 rounded"><p class="mb-0"></p>
                    Nuestro menú de temporada incluye productos horneados e incluso comidas completas perfectas para el desayuno, el almuerzo, la  merienda o la cena.
                    Obtenemos nuestros ingredientes de granjas orgánicas locales siempre que sea posible, junto con proveedores premium de productos especiales.</p></div>
              </div>
          </div>
      </div>
  </section>
  <section class="page-section">
      <div class="container">
          <div class="product-item">
              <div class="product-item-title d-flex">
                  <div class="bg-faded p-5 d-flex ms-auto rounded">
                      <h2 class="section-heading mb-0">
                          <span class="section-heading-upper">PROVENIENTES DE TODO EL MUNDO</span>
                          <p></p>
                          <span class="section-heading-lower">MAYORISTA EN MESCLAS ESPECIALES</span>
                      </h2>
                  </div>
              </div>
              <img class="product-item-img mx-auto d-flex rounded img-fluid mb-3 mb-lg-0" src="{% static 'core/imagenes/products-03.webp' %}" alt="..." />
              <div class="product-item-description d-flex me-auto">
                  <div class="bg-faded p-5 rounded"><p class="mb-0">
                    Viajar por el mundo en busca del café de la mejor calidad es algo de lo que estamos orgullosos. 
                    Cuando nos visites, siempre encontrarás nuevas mezclas de todo el mundo, principalmente de regiones de Centro y Sudamérica. 
                    Vendemos nuestras mezclas en cantidades mayorista y minorista. Visítenos en persona para obtener más detalles
                  </p>
                  </div>
              </div>
          </div>
      </div>
  </section>
  
  <div class="fs-3 pb-4 ">
    <a href="{% url 'producto:buscador_productos' %}">
      <h1 class="site-heading text-center text-faded d-none d-lg-block">
      <span class="site-heading-upper text-primary mb-3">CONSULTAR CATEGORIAS DE PRODUCTOS</span></a>
  </div> 
    
    </section>

    <div class="fs-3 pb-4 ">
      <a href="{% url 'producto:productocategoria_create' %}">
        <h1 class="site-heading text-center text-faded d-none d-lg-block">
        <span class="site-heading-upper text-primary mb-3">CREAR CATEGORÍAS DE PRODUCTO</span></a>
    </div> 

    <a href="{% url 'core:Home' %}">

      <section class="page-section bg-primary" id="about">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-lg-8 text-center">
                    <h2 class="text-white mt-0">VOLVER AL INCIO</h2>
                </div>
            </div>
        </div>
    </section>

      </a>

      <footer class="footer text-faded text-center py-5">
        <div class="container"><p class="m-0 small">La Esquina del Sabor &copy; 2024</p></div>
    </footer>
    {% endblock  %}
    

PROYECTO/producto/templates/producto/productos_caracteristicas.html
{% extends 'core/base.html' %}
{% load static %}

{% block contenido %}

<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Detalle de productos</title>
        <link href="{% static 'core/css/estilos.css' %}" rel="stylesheet"/>
    </head>

    <body>

        <ul>
            <li>Nombre: {{producto.nombre}}</li>
            <li>Categoría: {{producto.categoria}}</li>
            <li>Precio: $ {{producto.precio}}</li>
        </ul>

        <a href="{% url 'core:Home' %}">

            <section class="page-section bg-primary" id="about">
              <div class="container px-4 px-lg-5">
                  <div class="row gx-4 gx-lg-5 justify-content-center">
                      <div class="col-lg-8 text-center">
                          <h2 class="text-white mt-0">VOLVER AL INCIO</h2>
                      </div>
                  </div>
              </div>
          </section>

        <footer class="footer text-faded text-center py-5">
            <div class="container"><p class="m-0 small">La Esquina del Sabor &copy; 2024</p></div>
        </footer>

{% endblock contenido %}